name: diaperplugin
main: com.storynook.Plugin
version: 1.0.1
api-version: 1.19
author: ["StoryNook"]
description: "Bladder, bowels, diapers and more tracking, and usage"
# softdepend: [Vault]
commands:
  settings:
    description: "Open player settings for SNDP"
  pee:
    desctription: "Allows the player to wet themselves"
  poop:
    description: "Aloows the player to mess themselves"
  debug:
    description: "Used for debugging and testing. Admins & OP only"
  stats:
    description: "Shows the player's stats."
  check:
    description: "Shows Players Diaper Status"
  caregiver:
    description: "Manage your caregivers."
    usage: "/caregiver <add/remove/list> [player]"
  lockincon:
    description: "Used to lock a player's incontinance level"
    usage: "/lockincon <bladder|bowel|both> <Number> [player]"
  unlockincon:
    description: "Used to unlock a player's incontinance level"
    usage: "/unlockincon <bladder|bowel|both> [player]"
  minfill:
    description: "Used so players can set the min amount their stats need to be for a warning"
    usage: "/minfill <amount|help>"
  nightvision:
    description: "Toggles NightVision"
  nv:
    description: "Toggles NightVision"
permissions:
  diaperplugin.debug:
    description: "Permission to set bladder, bowels, and underwearType."
  diaperplugin.nightvision:
    description: "Allows the player to apply a nightvision effect"